fix: passing whole vite config to transformer will cause errors
Using Metro Bundler v0.82.4
BUNDLE  ../../packages/one/metro-entry.js
ERROR  ../../packages/one/metro-entry.js: resolveId(id) {
     const environment = this.environment;
     if (environment.depsOptimizer?.isOptimizedDep...<omitted>... } could not be cloned.
Error: ENOENT: no such file or directory, scandir '/.../assets'